// Central copy for the Danish UI — the active language (see ./index.ts).
// Mirrors en.ts key-for-key so the two stay easy to compare/extend. Only
// system-provided UI text belongs here: user-created list/template/item
// names, notes, and custom category/unit names are never translated (see
// domain/builtInLabels.ts for the built-in category/unit display mapping).
export const da = {
  appName: 'Indkøbsliste',
  nav: {
    lists: 'Lister',
    templates: 'Skabeloner',
    history: 'Historik',
    archive: 'Varearkiv',
    settings: 'Indstillinger',
  },
  common: {
    cancel: 'Annuller',
    save: 'Gem',
    delete: 'Slet',
    rename: 'Omdøb',
    duplicate: 'Duplikér',
    add: 'Tilføj',
    edit: 'Rediger',
    done: 'Færdig',
    back: '‹ Tilbage',
    close: 'Luk',
    confirm: 'Bekræft',
    undo: 'Fortryd',
    none: 'Ingen',
    other: 'Andet',
    optional: '(valgfri)',
    nameLabel: 'Navn',
    quantityLabel: 'Antal',
    unitLabel: 'Enhed',
    categoryLabel: 'Kategori',
    noteLabel: 'Note',
    nameRequiredError: 'Navn er påkrævet.',
  },
  lists: {
    screenTitle: 'Aktive lister',
    empty: 'Ingen aktive lister endnu — opret en for at komme i gang.',
    newListButton: '+ Ny liste',
    newListPlaceholder: 'f.eks. Ugentlige indkøb',
    remainingTemplate: '{count} tilbage',
    allDoneLabel: 'Alt er klaret',
    renameTitle: 'Omdøb liste',
    nameRequiredError: 'Listenavn er påkrævet.',
    deleteConfirmPrompt: 'Slet denne liste? Dette kan ikke fortrydes.',
    archiveButton: 'Arkivér som færdig',
    archiveConfirmPrompt:
      'Flyt denne liste til Historik som færdig? Du kan altid kopiere den tilbage til en ny liste.',
    duplicateButton: 'Duplikér',
    saveAsTemplateButton: 'Gem som skabelon',
    saveAsTemplatePrompt: 'Gem en kopi af denne liste som en genbrugelig skabelon.',
    templateNameLabel: 'Skabelonnavn',
    shareButton: 'Send kopi',
    importButton: 'Importér liste',
  },
  listDetail: {
    backButton: '‹ Lister',
    addItemHeading: 'Tilføj vare',
    itemNamePlaceholder: 'Varens navn',
    quantityPlaceholder: 'f.eks. 2 eller 2-3 eller 1 stor',
    addButton: 'Tilføj vare',
    addAnotherHint: 'Formularen forbliver åben, så du hurtigt kan tilføje flere varer.',
    addNoteButton: '+ Tilføj note',
    notePlaceholder: 'Valgfri note (mærke, smag, størrelse …)',
    hideCompleted: 'Skjul færdige',
    showCompleted: 'Vis færdige',
    completedHeading: 'Færdige varer',
    emptyItems: 'Ingen varer endnu — tilføj en ovenfor.',
    duplicateWarningTemplate: '"{name}" er allerede på denne liste.',
    combineButton: 'Kombinér antal',
    addSeparatelyButton: 'Tilføj alligevel som ny',
    deletedToast: 'Vare slettet.',
    completedToast: 'Vare sat som købt.',
    reopenedToast: 'Vare genåbnet.',
    editItemTitle: 'Rediger vare',
    deleteItemConfirmPrompt: 'Slet denne vare?',
    itemRowAriaTemplate: '{name}, antal {quantity}. Tryk for at redigere.',
    crossOffAria: 'Sæt vare som købt',
    reopenAria: 'Genåbn vare',
    deleteItemAria: 'Slet vare',
    quickAddNameAria: 'Varens navn',
    quickAddCategoryAria: 'Kategori',
    quickAddSubmitAria: 'Tilføj vare',
    quantityRequiredError: 'Antal er påkrævet.',
  },
  templates: {
    screenTitle: 'Skabeloner',
    empty: 'Ingen skabeloner endnu — gem en liste som skabelon, eller opret en her.',
    newTemplateButton: '+ Ny skabelon',
    newTemplatePlaceholder: 'f.eks. Ugentlige faste varer',
    renameTitle: 'Omdøb skabelon',
    nameRequiredError: 'Skabelonnavn er påkrævet.',
    deleteConfirmPrompt: 'Slet denne skabelon? Lister allerede oprettet fra den påvirkes ikke.',
    useTemplateButton: 'Opret liste herfra',
    useTemplatePrompt:
      'Navngiv den nye liste. Den starter som en uafhængig kopi — redigering af den ændrer aldrig denne skabelon.',
    newListNameLabel: 'Ny listes navn',
  },
  templateDetail: {
    backButton: '‹ Skabeloner',
    addItemHeading: 'Tilføj vare',
    addButton: 'Tilføj vare',
    emptyItems: 'Ingen varer endnu — tilføj en ovenfor.',
    editItemTitle: 'Rediger vare',
    deleteItemConfirmPrompt: 'Fjern denne vare fra skabelonen?',
    itemRowAriaTemplate: '{name}, antal {quantity}. Tryk for at redigere.',
    deleteItemAria: 'Slet vare',
  },
  history: {
    screenTitle: 'Historik',
    empty: 'Ingen arkiverede lister endnu — arkivér en færdig liste for at se den her.',
    backButton: '‹ Historik',
    archivedOnTemplate: 'Arkiveret {date}',
    itemsCountTemplate: '{count} varer',
    restoreButton: 'Kopiér til ny liste',
    restorePrompt:
      'Opret en ny aktiv liste ud fra denne arkiverede liste. Alle varer starter forfra (ikke afkrydset). Den arkiverede liste forbliver præcis som den er.',
    newListNameLabel: 'Ny listes navn',
    deleteConfirmPrompt: 'Slet denne arkiverede liste permanent? Dette kan ikke fortrydes.',
    shareButton: 'Send kopi',
  },
  archive: {
    screenTitle: 'Varearkiv',
    subtitle: 'Alle varenavne, du har tilføjet på denne enhed, husket til autofuldførelse.',
    empty: 'Dit varearkiv er tomt — varer, du tilføjer til en liste, vises her automatisk.',
    searchPlaceholder: 'Søg i varearkiv …',
    editItemTitle: 'Rediger arkiveret vare',
    deleteConfirmPrompt:
      'Fjern denne vare fra arkivet? Den bliver på de lister, den allerede er på.',
    usualCategoryLabel: 'Sædvanlig kategori',
    usualUnitLabel: 'Sædvanlig enhed',
    lastQuantityLabel: 'Seneste antal',
    deleteFromArchiveAria: 'Slet fra arkiv',
  },
  categories: {
    screenTitle: 'Kategorier',
    subtitle:
      'Sæt disse i den rækkefølge, du normalt går rundt i butikken — varer grupperes og sorteres sådan på alle lister.',
    newPlaceholder: 'Nyt kategorinavn',
    deleteConfirmPrompt: 'Slet denne kategori? Varer, der bruger den, flyttes til "Andet".',
    empty: 'Ingen kategorier endnu.',
    moveUpAria: 'Flyt op',
    moveDownAria: 'Flyt ned',
    renameAria: 'Omdøb',
    deleteAria: 'Slet',
  },
  units: {
    screenTitle: 'Enheder',
    newPlaceholder: 'Nyt enhedsnavn',
    deleteConfirmPrompt:
      'Slet denne enhed? Varer, der bruger den, viser den fortsat som ren tekst.',
    empty: 'Ingen enheder endnu.',
    renameAria: 'Omdøb',
    deleteAria: 'Slet',
  },
  settings: {
    screenTitle: 'Indstillinger',
    categoriesButton: 'Kategorier',
    unitsButton: 'Enheder',
    importButton: 'Importér en liste',
    backupHeading: 'Sikkerhedskopi',
    exportAllButton: 'Eksportér alle data',
    exportAllHint:
      'Gemmer alle lister, skabeloner, arkivposter, kategorier og enheder i én fil. Gør dette før du sletter appen, rydder browserdata eller skifter telefon — ellers er de data væk for altid.',
    restoreButton: 'Gendan fra sikkerhedskopi',
    aboutHeading: 'Om appen',
    aboutBody:
      'Alle data forbliver kun på denne enhed — der er ingen konto, ingen server, og ingen deling mellem telefoner, medmindre du udtrykkeligt sender eller importerer en fil. Installation af appen på en anden telefon starter med tomme, uafhængige data.',
  },
  importList: {
    title: 'Importér liste',
    pickFileButton: 'Vælg fil …',
    invalidFileError: 'Denne fil kunne ikke læses som en gyldig indkøbsliste-fil.',
    previewItemsTemplate: '{count} varer',
    nameConflictWarning: 'En liste ved navn "{name}" findes allerede.',
    newNameLabel: 'Importér som',
    importButton: 'Importér som ny liste',
    successTemplate: 'Importerede "{name}" som en ny liste.',
  },
  backup: {
    exportSuccessToast: 'Sikkerhedskopi gemt.',
    restoreTitle: 'Gendan fra sikkerhedskopi',
    pickFileButton: 'Vælg sikkerhedskopi-fil …',
    invalidFileError: 'Denne fil kunne ikke læses som JSON.',
    strategyLabel: 'Hvordan skal denne sikkerhedskopi gendannes?',
    strategyMerge: 'Flet',
    strategyMergeHint:
      'Tilføjer det, der mangler, og opdaterer poster, hvor sikkerhedskopien har en nyere version. Intet eksisterende slettes.',
    strategyReplace: 'Erstat alt',
    strategyReplaceHint:
      'Sletter alle data på denne enhed nu og erstatter dem med præcis det, der er i sikkerhedskopien.',
    replaceConfirmPrompt:
      'Dette sletter alle lister, skabeloner, arkivposter, kategorier og enheder på denne enhed og erstatter dem med sikkerhedskopien. Dette kan ikke fortrydes.',
    restoreButton: 'Gendan',
    mergeSummaryTemplate: 'Flettet: {listsAdded} lister tilføjet, {listsUpdated} opdateret.',
    replaceSuccessToast: 'Alle data er erstattet fra sikkerhedskopien.',
  },
  a11y: {
    mainNav: 'Hovedmenu',
    moreActions: 'Flere handlinger',
  },
} as const
