// Central copy for the English UI. Every user-facing string in the app
// should live here rather than inline in components, matching GolfStats and
// TrainTrack's convention so a future locale file can be added without
// touching component code.
export const en = {
  appName: 'Shopping List',
  nav: {
    lists: 'Lists',
    templates: 'Templates',
    history: 'History',
    archive: 'Archive',
    settings: 'Settings',
  },
  common: {
    cancel: 'Cancel',
    save: 'Save',
    delete: 'Delete',
    rename: 'Rename',
    duplicate: 'Duplicate',
    add: 'Add',
    edit: 'Edit',
    done: 'Done',
    back: '‹ Back',
    close: 'Close',
    confirm: 'Confirm',
    undo: 'Undo',
    none: 'None',
    other: 'Other',
    optional: '(optional)',
    nameLabel: 'Name',
    quantityLabel: 'Quantity',
    unitLabel: 'Unit',
    categoryLabel: 'Category',
    noteLabel: 'Note',
  },
  lists: {
    screenTitle: 'Lists',
    empty: 'No active lists yet — create one to start shopping.',
    newListButton: '+ New list',
    newListPlaceholder: 'e.g. Weekly shopping',
    remainingTemplate: '{count} left',
    allDoneLabel: 'All done',
    renameTitle: 'Rename list',
    deleteConfirmPrompt: 'Delete this list? This cannot be undone.',
    archiveButton: 'Archive as done',
    archiveConfirmPrompt:
      'Move this list to History as done? You can copy it back into a new list any time.',
    duplicateButton: 'Duplicate',
    saveAsTemplateButton: 'Save as template',
    saveAsTemplatePrompt: 'Save a copy of this list as a reusable template.',
    templateNameLabel: 'Template name',
    shareButton: 'Send copy',
    importButton: 'Import list',
  },
  listDetail: {
    backButton: '‹ Lists',
    addItemHeading: 'Add item',
    itemNamePlaceholder: 'Item name',
    quantityPlaceholder: 'e.g. 2 or 2-3 or 1 large',
    addButton: 'Add item',
    addAnotherHint: 'Keeps adding — the form stays open for the next item.',
    addNoteButton: '+ Add note',
    notePlaceholder: 'Optional note (brand, flavour, size…)',
    hideCompleted: 'Hide completed',
    showCompleted: 'Show completed',
    completedHeading: 'Completed',
    emptyItems: 'No items yet — add one above.',
    duplicateWarningTemplate: '"{name}" is already on this list.',
    combineButton: 'Combine quantities',
    addSeparatelyButton: 'Add separately anyway',
    deletedToast: 'Item deleted.',
    completedToast: 'Item crossed off.',
    reopenedToast: 'Item reopened.',
    editItemTitle: 'Edit item',
    deleteItemConfirmPrompt: 'Delete this item?',
  },
  templates: {
    screenTitle: 'Templates',
    empty: 'No templates yet — save a list as a template, or create one here.',
    newTemplateButton: '+ New template',
    newTemplatePlaceholder: 'e.g. Weekly staples',
    renameTitle: 'Rename template',
    deleteConfirmPrompt: 'Delete this template? Lists already created from it are not affected.',
    useTemplateButton: 'Create list from this',
    useTemplatePrompt:
      'Name the new list. It starts as an independent copy — editing it will never change this template.',
    newListNameLabel: 'New list name',
  },
  templateDetail: {
    backButton: '‹ Templates',
    addItemHeading: 'Add item',
    addButton: 'Add item',
    emptyItems: 'No items yet — add one above.',
    editItemTitle: 'Edit item',
    deleteItemConfirmPrompt: 'Remove this item from the template?',
  },
  history: {
    screenTitle: 'History',
    empty: 'No archived lists yet — archive a completed list to see it here.',
    backButton: '‹ History',
    archivedOnTemplate: 'Archived {date}',
    itemsCountTemplate: '{count} items',
    restoreButton: 'Copy into new list',
    restorePrompt:
      'Create a new active list from this archived one. Every item starts fresh (not crossed off). The archived list stays exactly as it is.',
    newListNameLabel: 'New list name',
    deleteConfirmPrompt: 'Permanently delete this archived list? This cannot be undone.',
    shareButton: 'Send copy',
  },
  archive: {
    screenTitle: 'Item archive',
    subtitle: 'Every item name you have added on this device, remembered for autocomplete.',
    empty: 'Your item archive is empty — items you add to a list appear here automatically.',
    searchPlaceholder: 'Search archived items…',
    editItemTitle: 'Edit archived item',
    deleteConfirmPrompt:
      'Remove this item from the archive? It stays on any lists it is already on.',
    usualCategoryLabel: 'Usual category',
    usualUnitLabel: 'Usual unit',
    lastQuantityLabel: 'Last quantity',
  },
  categories: {
    screenTitle: 'Categories',
    subtitle:
      'Arrange these in the order you usually walk the store — items are grouped and sorted this way on every list.',
    newPlaceholder: 'New category name',
    deleteConfirmPrompt: 'Delete this category? Items already using it move to "Other".',
    empty: 'No categories yet.',
  },
  units: {
    screenTitle: 'Units',
    newPlaceholder: 'New unit name',
    deleteConfirmPrompt: 'Delete this unit? Items already using it keep showing it as plain text.',
    empty: 'No units yet.',
  },
  settings: {
    screenTitle: 'Settings',
    categoriesButton: 'Categories',
    unitsButton: 'Units',
    importButton: 'Import a list',
    backupHeading: 'Backup',
    exportAllButton: 'Export all data',
    exportAllHint:
      'Saves every list, template, archive entry, category and unit to one file. Do this before deleting the app, clearing browser data, or switching phones — otherwise that data is gone for good.',
    restoreButton: 'Restore from backup',
    aboutHeading: 'About',
    aboutBody:
      'All data stays on this device only — there is no account, no server, and no sharing between phones except when you explicitly send or import a file. Installing this app on another phone starts with empty, independent data.',
  },
  importList: {
    title: 'Import list',
    pickFileButton: 'Choose file…',
    invalidFile: 'invalid file',
    previewItemsTemplate: '{count} items',
    nameConflictWarning: 'A list named "{name}" already exists.',
    newNameLabel: 'Import as',
    importButton: 'Import as new list',
    successTemplate: 'Imported "{name}" as a new list.',
  },
  backup: {
    exportSuccessToast: 'Backup saved.',
    restoreTitle: 'Restore from backup',
    pickFileButton: 'Choose backup file…',
    strategyLabel: 'How should this backup be restored?',
    strategyMerge: 'Merge',
    strategyMergeHint:
      'Adds anything missing and updates records the backup has a newer copy of. Nothing existing is deleted.',
    strategyReplace: 'Replace everything',
    strategyReplaceHint:
      'Wipes all data currently on this device and replaces it with exactly what is in the backup.',
    replaceConfirmPrompt:
      'This deletes every list, template, archive entry, category and unit currently on this device and replaces them with the backup. This cannot be undone.',
    restoreButton: 'Restore',
    mergeSummaryTemplate: 'Merged: {listsAdded} lists added, {listsUpdated} updated.',
    replaceSuccessToast: 'All data replaced from backup.',
  },
} as const
